# Generated by Django 4.0.4 on 2022-05-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='picture',
        ),
    ]
