# Generated by Django 3.2.12 on 2022-04-09 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220407_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
