# Generated by Django 3.2.12 on 2022-04-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_articles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
