# Generated by Django 4.0.3 on 2022-04-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_articles_likes_articles_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='like',
            new_name='post',
        ),
    ]
