<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-04-19 01:11
=======
# Generated by Django 4.0.3 on 2022-04-15 09:46
>>>>>>> 54bb26102ee6cd0556aac7a797ad3b619b5c45a3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_articles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, default='images/default/images.png', null=True, upload_to='images'),
        ),
    ]
