# Generated by Django 4.0.3 on 2022-04-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='total',
            new_name='notification_type',
        ),
    ]
