# Generated by Django 3.2.12 on 2022-04-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_articles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='picture',
            field=models.ImageField(blank=True, default='images/default/images.png', null=True, upload_to='images'),
        ),
    ]
