# Generated by Django 3.2.6 on 2022-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_likes_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
