# Generated by Django 4.0.3 on 2022-04-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_notification_comment_alter_notification_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
