# Generated by Django 4.0.3 on 2022-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default/defaultProfile.png', upload_to='profile_pics'),
        ),
    ]
