# Generated by Django 4.0.4 on 2022-05-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_chatmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatModel',
        ),
    ]
